const GT={
 init(){load();theme();this.render();document.getElementById("profileModal").classList.toggle("on",!localStorage.getItem("gt7_user"))},
 selectUser(u){currentUser=u;localStorage.setItem("gt7_user",u);load();theme();this.render();document.getElementById("profileModal").classList.remove("on")},
 openUsers(){document.getElementById("profileModal").classList.add("on")},
 show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));document.getElementById(id).classList.add("on");document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("on",b.dataset.nav===id));if(id==="data")document.getElementById("data").innerHTML=renderStats();if(id==="plan")document.getElementById("plan").innerHTML=renderPlan();if(id==="routines")this.renderRoutines()},
 render(){theme();document.getElementById("todayLabel").textContent=today();let meta=USERS[currentUser];document.getElementById("userChip").textContent=`${meta.icon} ${currentUser}`;this.renderHome();this.renderRoutines();if(document.getElementById("data").classList.contains("on"))document.getElementById("data").innerHTML=renderStats();if(document.getElementById("plan").classList.contains("on"))document.getElementById("plan").innerHTML=renderPlan()},
 todayRoutine(){let p=S.plan[today()];if(p?.routineId)return rt(p.routineId);return S.routines[0]||null},
 renderHome(){let r=this.todayRoutine(),done=S.plan[today()]?.status==="done";document.getElementById("home").innerHTML=`<div class="card hero"><div class="muted">Buenos días ${currentUser}</div><h1>${done?"Hoy ya has entrenado":r?"Hoy toca":"Sin rutina"}</h1><p class="muted">${done?"Buen trabajo. Próximo: descanso o siguiente plan.":r?r.name:"Importa o crea una rutina para empezar."}</p>${r?`<div class="routinePreview">${r.items.map(i=>`<div>${ex(i.exerciseId)?.name||"Ejercicio"} · ${i.sets} series · ${i.mode==="time"?(i.repsPlan[0]+"s"):i.mode==="failure"?"fallo":(i.repsPlan[0]+" reps")}</div>`).join("")}</div><button class="wall primary bigAction" onclick="startRoutine('${r.id}')">${done?"Repetir entreno":"Comenzar"}</button>`:`<button class="wall primary" onclick="GT.show('routines')">Ir a rutinas</button>`}</div>`},
 renderRoutines(){let el=document.getElementById("routines");if(!el)return;el.innerHTML=`<div class="card importBox"><h2>Importar rutina</h2><div class="helpBox">Formatos: <b>4x8</b>, <b>4x10-12</b>, <b>4x fallo</b>, <b>4x20s</b>, <b>80kg</b>, <b>descanso 180</b>.</div><pre>Press banca 4x8 80kg descanso 180
Dominadas 4x fallo descanso 180
L-Sit 4x20s descanso 90</pre><input id="importName" placeholder="Nombre de rutina"><textarea id="importText" placeholder="Pega aquí la rutina"></textarea><div class="row"><button class="wall primary" onclick="importRoutine()">Importar rutina</button><button onclick="exampleImport()">Ejemplo</button></div></div><div class="card"><h2>Mis rutinas</h2><button onclick="createRoutine()">Crear vacía</button>${S.routines.map(r=>`<div class="routineCard"><details><summary><strong>${r.name}</strong><div class="muted">${r.items.length} ejercicios</div></summary><div class="row"><button class="primary" onclick="startRoutine('${r.id}')">Comenzar</button><button onclick="assignToday('${r.id}')">Asignar hoy</button><button onclick="renameRoutine('${r.id}')">Renombrar</button><button onclick="duplicateRoutine('${r.id}')">Duplicar</button><button class="danger" onclick="deleteRoutine('${r.id}')">Borrar</button></div>${r.items.map(i=>`<div class="routineItem"><b>${ex(i.exerciseId)?.name}</b><input type="number" value="${i.sets}" onchange="updItem('${r.id}','${i.id}','sets',this.value)" title="series"><input type="number" value="${i.repsPlan[0]||0}" onchange="updItem('${r.id}','${i.id}','reps',this.value)" title="reps/seg"><input type="number" step=".25" value="${i.weight||0}" onchange="updItem('${r.id}','${i.id}','weight',this.value)" title="kg"><button class="danger" onclick="delItem('${r.id}','${i.id}')">×</button><select onchange="updItem('${r.id}','${i.id}','mode',this.value)"><option value="reps" ${i.mode==="reps"?"selected":""}>reps</option><option value="time" ${i.mode==="time"?"selected":""}>tiempo</option><option value="failure" ${i.mode==="failure"?"selected":""}>fallo</option></select><input type="number" value="${i.rest||S.settings.rest||120}" onchange="updItem('${r.id}','${i.id}','rest',this.value)" title="descanso"></div>`).join("")}<button onclick="addExercise('${r.id}')">Añadir ejercicio</button><div class="editorNote">Los cambios se guardan automáticamente.</div></details></div>`).join("")||"<p class='muted'>No hay rutinas.</p>"}</div>`},
};
window.addEventListener("load",()=>GT.init());
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
