function volumeForSession(sid){return S.sets.filter(x=>x.sessionId===sid).reduce((a,x)=>a+(+x.weight||0)*(+x.reps||0),0)}
function relativeStrength(){let bw=S.profile?.bodyWeight||S.weights.at(-1)?.weight||0;if(!bw)return "—";let max=Math.max(0,...S.sets.map(s=>(+s.weight||0)));return max?Math.round((max/bw)*100)/100:"—"}
function editSet(sid,setid,k,v){let s=S.sets.find(x=>x.id===setid);if(!s)return;s[k]=+v;save()}
function saveHistoryEdit(){save();GT.render();alert("Entreno guardado")}
function deleteSession(sid){let sess=S.sessions.find(x=>x.id===sid);if(!sess)return;if(!confirm("¿Mover entreno a papelera?"))return;S.trash=S.trash||{routines:[],blocks:[],sessions:[]};S.trash.sessions.push({...sess,sets:S.sets.filter(x=>x.sessionId===sid),deletedAt:now()});S.sessions=S.sessions.filter(x=>x.id!==sid);S.sets=S.sets.filter(x=>x.sessionId!==sid);save();GT.render()}
function copyCoach(sid){navigator.clipboard?.writeText(coachReport(sid));alert("Coach Report copiado")}
function editSessionNote(sid,v){let sess=S.sessions.find(x=>x.id===sid);if(sess){sess.note=v;save()}}
function coachReport(sid){let sess=S.sessions.find(x=>x.id===sid),r=rt(sess.routineId),sets=S.sets.filter(x=>x.sessionId===sid);let out=`${sess?.date||""}\n${r?.name||"Rutina"}\n\n`;let by={};sets.forEach(x=>(by[x.exerciseId]=by[x.exerciseId]||[]).push(x));Object.entries(by).forEach(([eid,ss])=>{out+=`${ex(eid)?.name||"Ejercicio"}\n`;ss.forEach(x=>out+=x.mode==="time"?`${x.reps}s\n`:`${x.weight||0}kg × ${x.reps||0}${x.pr?" 🏆":""}\n`);out+="\n"});out+=`Volumen: ${Math.round(volumeForSession(sid))} kg`;return out}
function bestByExercise(eid){let ss=S.sets.filter(x=>x.exerciseId===eid);if(!ss.length)return null;return ss.sort((a,b)=>((+b.weight||0)*(+b.reps||0))-((+a.weight||0)*(+a.reps||0)))[0]}
function exerciseEvolution(eid){let data=S.sessions.map(sess=>{let ss=S.sets.filter(x=>x.sessionId===sess.id&&x.exerciseId===eid);let best=ss.length?Math.max(...ss.map(x=>(+x.weight||0)*(+x.reps||0))):0;return{date:sess.date,best}}).filter(x=>x.best>0).slice(-10);let max=Math.max(1,...data.map(x=>x.best));return `<div class="spark">${data.map(x=>`<div class="sparkBar" style="height:${Math.max(5,x.best/max*100)}px" title="${x.date}: ${Math.round(x.best)}"></div>`).join("")}</div>`}
function renderHistoryCard(sess){let r=rt(sess.routineId),ss=S.sets.filter(x=>x.sessionId===sess.id);return `<details class="historyCard"><summary><h3>${r?.name||"Rutina"} · ${sess.date}</h3><p class="muted">${ss.length} series · ${Math.round(volumeForSession(sess.id))} kg</p></summary><div class="coachReportBox">${coachReport(sess.id)}</div><div class="editSaveBar"><button class="primary" onclick="copyCoach('${sess.id}')">Copiar</button><button onclick="saveHistoryEdit()">Guardar cambios</button></div><textarea class="noteArea" placeholder="Nota del entreno" onchange="editSessionNote('${sess.id}',this.value)">${sess.note||""}</textarea>${ss.map(st=>`<div class="setEditRow"><span>${ex(st.exerciseId)?.name||"Ejercicio"} S${st.setNumber} ${st.pr?"🏆":""}</span><input type="number" step=".25" value="${st.weight||0}" onchange="editSet('${sess.id}','${st.id}','weight',this.value)"><input type="number" value="${st.reps||0}" onchange="editSet('${sess.id}','${st.id}','reps',this.value)"></div>`).join("")}<button class="danger" onclick="deleteSession('${sess.id}')">Borrar entreno</button></details>`}
function renderStats(){let totalVol=Math.round(S.sets.reduce((a,x)=>a+(+x.weight||0)*(+x.reps||0),0));let lastW=S.profile?.bodyWeight||S.weights.at(-1)?.weight||"—";let sessions=S.sessions.slice(-10);let max=Math.max(1,...sessions.map(s=>volumeForSession(s.id)));let chart=sessions.map(s=>`<div class="barMini" style="height:${Math.max(5,volumeForSession(s.id)/max*140)}px" title="${s.date}"></div>`).join("");let exerciseIds=[...new Set(S.sets.map(x=>x.exerciseId))];let prCards=exerciseIds.map(eid=>{let b=bestByExercise(eid);return b?`<div class="metric"><span>${ex(eid)?.name||"Ejercicio"}</span><b>${b.weight}×${b.reps}</b></div>`:""}).join("");let evo=exerciseIds.slice(0,8).map(eid=>`<div class="exerciseChartCard"><h3>${ex(eid)?.name||"Ejercicio"}</h3>${exerciseEvolution(eid)}</div>`).join("");let hist=S.sessions.slice().reverse().map(renderHistoryCard).join("");return `<div class="card"><h2>Estadísticas PRO</h2><div class="statGrid"><div class="metric"><span>Sesiones</span><b>${S.sessions.length}</b></div><div class="metric"><span>Volumen</span><b>${totalVol}</b></div><div class="metric"><span>Peso corporal</span><b>${lastW}</b></div><div class="metric"><span>Fuerza relativa</span><b>${relativeStrength()}</b></div></div><h3>Volumen últimos entrenos</h3><div class="chart">${chart}</div></div><div class="card"><h2>PR por ejercicio</h2><div class="statGrid">${prCards||"<p class='muted'>Sin PR todavía.</p>"}</div></div><div class="card"><h2>Evolución por ejercicio</h2>${evo||"<p class='muted'>Sin datos.</p>"}</div><div class="card"><h2>Peso corporal</h2><button onclick="addWeight()">Registrar peso</button></div><div class="card"><h2>Historial plegado</h2><p class="editSessionHelp">Abre un entreno, edita, copia o guarda cambios.</p>${hist||"<p class='muted'>Sin entrenos guardados.</p>"}</div>`}
function addWeight(){let w=+(prompt("Peso corporal kg",String(S.profile?.bodyWeight||""))||0);if(w){S.profile=S.profile||{};S.profile.bodyWeight=w;S.weights.push({date:today(),weight:w});save();GT.render()}}
function saveBodyWeightFromHome(){let el=document.getElementById("homeBodyWeight");let w=+(el?.value||0);if(!w){alert("Introduce un peso válido.");return}S.profile=S.profile||{};S.profile.bodyWeight=w;S.weights=S.weights||[];S.weights.push({date:today(),weight:w});save();GT.render();alert("Peso corporal guardado")}
