let A=null,timer=null,execTimer=null;
function currentRoutine(){return A?rt(A.session.routineId):null}
function currentItem(){let r=currentRoutine();return r&&r.items?r.items[A.idx]:null}
function currentSet(){let it=currentItem();return it?(A.done[it.id]||0)+1:1}
function startRoutine(rid){let r=rt(rid);if(!r||!r.items||!r.items.length){alert('Rutina vacía');return}A={session:{id:id(),date:today(),routineId:rid,start:now(),note:''},idx:0,done:{},sets:[]};saveActiveWorkout(A);GT.show('workout');renderWorkout()}
function bestSetForExercise(eid){let ss=(S.sets||[]).filter(x=>x.exerciseId===eid);if(!ss.length)return null;return ss.slice().sort((a,b)=>((+b.weight||0)*(+b.reps||0))-((+a.weight||0)*(+a.reps||0)))[0]}
function isPRSet(eid,w,r){let b=bestSetForExercise(eid);if(!b)return (+w||0)>0||(+r||0)>0;return ((+w||0)*(+r||0))>((+b.weight||0)*(+b.reps||0))}
function lastSetsForExercise(eid){for(let sess of (S.sessions||[]).slice().reverse()){let ss=(S.sets||[]).filter(x=>x.sessionId===sess.id&&x.exerciseId===eid);if(ss.length)return ss}return[]}
function lastSessionHtml(eid,mode){let last=lastSetsForExercise(eid);if(!last.length)return 'Sin datos previos';return last.map(s=>mode==='time'?`${s.reps}s`:`${s.weight||0}kg × ${s.reps||0}`).join('<br>')}
function suggestionForItem(it){let last=lastSetsForExercise(it.exerciseId);if(!last.length)return 'Sin datos previos';let target=it.repsPlan?.[0]||0;let ok=last.every(s=>(+s.reps||0)>=target);if(ok&&it.mode==='reps')return `Puedes probar +${S.settings?.inc||2.5} kg`;if(ok&&it.mode==='time')return 'Puedes subir segundos';return 'Mantener'}
function recordSet(reps,weight){let it=currentItem();if(!it){endWorkout();return}let set=currentSet(),e=ex(it.exerciseId);if(!e){alert('Ejercicio no encontrado');return}let pr=false;A.sets.push({id:id(),sessionId:A.session.id,exerciseId:e.id,setNumber:set,reps:+reps||0,weight:+weight||0,result:'normal',order:A.idx,mode:it.mode,pr});if(weight>0){e.lastWeight=+weight;if(!e.defaultWeight)e.defaultWeight=+weight}A.done[it.id]=set;saveActiveWorkout(A);if(pr&&weight>0)setTimeout(()=>alert('🏆 Nuevo PR: '+e.name+' '+weight+'kg x '+reps),50);if(set>=(+it.sets||1)){if(A.idx>=currentRoutine().items.length-1){endWorkout();return}A.idx++;saveActiveWorkout(A);renderWorkout();return}startRest(it.rest||S.settings?.rest||120)}
function finishSet(){let it=currentItem();if(!it){endWorkout();return}let set=currentSet();if(it.mode==='time'){startExecutionTimer(it.repsPlan?.[set-1]||it.repsPlan?.[0]||ex(it.exerciseId)?.defaultTime||S.settings?.defaultTime||20);return}let target=it.mode==='failure'?0:(it.repsPlan?.[set-1]||it.repsPlan?.[0]||0);let reps=it.mode==='failure'?+(prompt('Reps realizadas','0')||0):+(prompt('Reps realizadas',String(target))||target);let e=ex(it.exerciseId),w0=it.weight||e?.lastWeight||e?.defaultWeight||0;let weight=+(prompt('Peso usado',String(w0))||0);recordSet(reps,weight)}
function startExecutionTimer(sec){let left=+sec||20,it=currentItem(),e=it?ex(it.exerciseId):null;clearInterval(execTimer);document.getElementById('workout').innerHTML=`<div class="timer"><div class="casio"><div class="lcd"><div>EJERCICIO</div><div id="execTime" class="lcdTime">${fmt(left)}</div><div>${e?.name||'Ejercicio'}</div><div class="inlineActions"><button class="wall primary" onclick="completeTimedSet(${left})">Completar</button><button onclick="stopTimedSet()">Parar</button></div></div></div></div>`;execTimer=setInterval(()=>{left--;let el=document.getElementById('execTime');if(el)el.textContent=fmt(left);if(left<=0){clearInterval(execTimer);beep();buzz();completeTimedSet(sec)}},1000)}
function completeTimedSet(t){clearInterval(execTimer);let done=+(prompt('Segundos realizados',String(t))||t);recordSet(done,0)}
function stopTimedSet(){clearInterval(execTimer);let done=+(prompt('Segundos realizados','0')||0);recordSet(done,0)}
function startRest(sec){let left=+sec||120;clearInterval(timer);document.getElementById('workout').innerHTML=`<div class="timer"><div class="casio"><div class="lcd"><div>DESCANSO</div><div id="lcdTime" class="lcdTime">${fmt(left)}</div><div>Siguiente: ${nextName()}</div><button class="wall primary" onclick="skipRest()">Saltar</button></div></div></div>`;timer=setInterval(()=>{left--;let el=document.getElementById('lcdTime');if(el)el.textContent=fmt(left);if(left<=0){beep();buzz();skipRest()}},1000)}
function skipRest(){clearInterval(timer);if(A&&A.pendingNextExercise){A.pendingNextExercise=false;A.idx++;saveActiveWorkout(A)}renderWorkout()}
function fmt(s){s=Math.max(0,+s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function nextName(){let it=currentItem();return it?ex(it.exerciseId)?.name||'Siguiente':'Fin'}
function coachSummary(sid){let sess=(S.sessions||[]).find(x=>x.id===sid),r=sess?rt(sess.routineId):null,sets=(S.sets||[]).filter(x=>x.sessionId===sid);let vol=sets.reduce((a,x)=>a+(+x.weight||0)*(+x.reps||0),0);let out=`${r?.name||'Rutina'} · ${sess?.date||today()}\n\nSeries: ${sets.length}\nVolumen: ${Math.round(vol)} kg\n\n`;let by={};sets.forEach(x=>(by[x.exerciseId]=by[x.exerciseId]||[]).push(x));Object.entries(by).forEach(([eid,ss])=>{out+=`${ex(eid)?.name||'Ejercicio'}\n`;ss.forEach(x=>out+=x.mode==='time'?`${x.reps}s\n`:`${x.weight||0}kg x ${x.reps||0}${x.pr?' 🏆':''}\n`);out+='\n'});return out}
function endWorkout(){if(!A)return;A.session.end=now();S.sessions=S.sessions||[];S.sets=S.sets||[];let previousSets=(S.sets||[]).slice();let prExercises=[];let grouped={};A.sets.forEach(st=>(grouped[st.exerciseId]=grouped[st.exerciseId]||[]).push(st));Object.entries(grouped).forEach(([eid,ss])=>{let oldBest=Math.max(0,...previousSets.filter(x=>x.exerciseId===eid).map(x=>(+x.weight||0)*(+x.reps||0)));let best=ss.slice().sort((a,b)=>((+b.weight||0)*(+b.reps||0))-((+a.weight||0)*(+a.reps||0)))[0];let newBest=(+best.weight||0)*(+best.reps||0);if(newBest>oldBest&&newBest>0){best.pr=true;prExercises.push(ex(eid)?.name||"Ejercicio")}});S.sessions.push(A.session);S.sets.push(...A.sets);S.plan=S.plan||{};S.plan[today()]={date:today(),type:'done',routineId:A.session.routineId,status:'done'};save();if(typeof postWorkoutBackup==='function')postWorkoutBackup();clearActiveWorkout();let sid=A.session.id,summary=coachSummary(sid);if(prExercises.length){summary+="\n🏆 PR por ejercicio: "+prExercises.join(", ")+"\n";beep();buzz(220)}A=null;GT.show('home');GT.render();setTimeout(()=>showFinalSummary(summary,sid),100)}
function showFinalSummary(txt,sid){let sets=(S.sets||[]).filter(x=>x.sessionId===sid),vol=sets.reduce((a,x)=>a+(+x.weight||0)*(+x.reps||0),0),prs=sets.filter(x=>x.pr).length,box=document.getElementById('summaryBox');if(!box){alert(txt);return}box.innerHTML=`<h2>Resumen final</h2><div class="summaryStats"><div class="metric"><span>Series</span><b>${sets.length}</b></div><div class="metric"><span>Volumen</span><b>${Math.round(vol)}</b></div><div class="metric"><span>PR</span><b>${prs}</b></div></div><div class="coachReportBox">${txt}</div><div class="row"><button class="primary" onclick="navigator.clipboard?.writeText(document.querySelector('#summaryBox .coachReportBox').innerText);alert('Copiado')">Copiar</button><button onclick="GT.show(\'data\');document.getElementById(\'summaryOverlay\').classList.remove(\'on\')">Editar en historial</button><button onclick="document.getElementById(\'summaryOverlay\').classList.remove(\'on\')">Cerrar</button></div>`;document.getElementById('summaryOverlay')?.classList.add('on')}
function renderWorkout(){let r=currentRoutine(),it=currentItem();if(!A||!r||!it){document.getElementById('workout').innerHTML='<div class="card"><h2>No hay entrenamiento activo</h2><button class="primary" onclick="GT.show(\'home\')">Volver</button></div>';return}let e=ex(it.exerciseId);if(!e){document.getElementById('workout').innerHTML='<div class="card"><h2>Ejercicio no encontrado</h2><button onclick="A.idx++;renderWorkout()">Saltar</button></div>';return}let set=currentSet(),target=it.mode==='failure'?'F':(it.repsPlan?.[set-1]||it.repsPlan?.[0]||0),label=it.mode==='time'?'Segundos':'Reps',best=bestSetForExercise(it.exerciseId);document.getElementById('workout').innerHTML=`<div class="card focus"><div><div class="muted">${r.name}</div><div class="focusTitle">${e.name}</div><div class="timeBadge">${it.mode==='time'?'Ejercicio por tiempo':it.mode==='failure'?'Al fallo':'Repeticiones'} ${it.superset?`<span class="supersetBadge">SS ${it.superset}</span>`:''}</div><div class="lastBox"><strong>Última sesión</strong><br>${lastSessionHtml(it.exerciseId,it.mode)}<br><br><strong>Mejor marca</strong><br>${best?(best.weight+'kg × '+best.reps):'Sin PR'}<br><br><strong>Sugerencia</strong><br>${suggestionForItem(it)}<div class="restMini">Descanso: ${fmt(it.rest||S.settings?.rest||120)}</div></div></div><div class="focusStats"><div class="focusStat"><span>Serie</span><b>${set}/${it.sets||1}</b></div><div class="focusStat"><span>${label}</span><b>${target}</b></div><div class="focusStat"><span>Peso</span><b>${it.mode==='time'?'—':(it.weight||e.lastWeight||e.defaultWeight||0)}</b><small>${it.mode==='time'?'':'kg'}</small></div></div><button class="wall primary bigAction ${it.mode==='time'?'timeAction':''}" onclick="finishSet()">${it.mode==='time'?'Iniciar crono':'Fin serie'}</button><div class="row"><button onclick="A.idx=Math.max(0,A.idx-1);saveActiveWorkout(A);renderWorkout()">Anterior</button><button onclick="A.idx=Math.min(r.items.length-1,A.idx+1);saveActiveWorkout(A);renderWorkout()">Siguiente</button><button class="danger" onclick="endWorkout()">Finalizar</button></div></div>`}
function resumeActiveWorkout(){
 let old=getActiveWorkout();
 if(!old)return false;
 A=old;
 document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));
 document.getElementById("workout").classList.add("on");
 document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("on",b.dataset.nav==="workout"));
 renderWorkout();
 return true
}
function discardActiveWorkout(){if(confirm('¿Descartar entrenamiento en curso?')){clearActiveWorkout();GT.render()}}

window.addEventListener('beforeunload',()=>{try{if(A)saveActiveWorkout(A)}catch(e){}});
function pauseWorkoutToHome(){if(A)saveActiveWorkout(A);GT.show("home");GT.render();}
