const CACHE="gymtracker-phoenix-11-alpha-build-018-forge-foundation";
const VERSION="018";
const ASSETS=["./","./index.html?v=018","./actualizar-apex.html?v=018","./styles.css?v=018","./app.js?v=018","./manifest.webmanifest?v=018","./favicon-32.png?v=018","./favicon-48.png?v=018","./apple-touch-icon.png?v=018","./icon-192.png","./icon-512.png","./phoenix-master-1024.png","./core/network-gate.js?v=018","./core/sync-provider.js?v=018","./themes/material-contract.js?v=018","./themes/component-contract.js?v=018","./themes/material-engine.js?v=018","./themes/component-runtime.js?v=018","./forge/contracts/shape-contract.js?v=018","./forge/core/forge-action-bus.js?v=018","./forge/core/forge-view-model.js?v=018","./forge/core/forge-diagnostics.js?v=018","./forge/engine/shape-engine.js?v=018","./forge/contracts/schemas/shape.schema.json","./forge/shapes/precision/manifest.json","./forge/shapes/precision/shape.json","./themes/precision/manifest.json","./themes/precision/tokens.css","./themes/precision/components.css","./themes/precision/timer.css","./themes/apex/manifest.json","./themes/apex/apex.css?v=018","./js/pedb-bundle.js?v=018","./js/pedb-db.js?v=018","./js/pedb-loader.js?v=018","./data/muscles.json","./data/zones.json","./data/equipment.json","./data/patterns.json","./data/exercise_types.json","./data/families.json","./data/exercises.json","./data/relations.json","./data/manifest.json","./data/search_index.json","./data/user_relation_rules.json","./data/family_knowledge.json","./data/equipment_profiles_schema.json","./data/reason_templates.json","./data/tags.json","./data/packs.json","./data/equipment_meta.json","./data/anatomy.json","./data/functions.json","./templates/PEDB_Ejercicios_Manuales.csv","./templates/PEDB_Ejercicios_Manuales.json","./audio/phoenix-apex-ready.wav"];
self.addEventListener("install",event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("gymtracker-phoenix")&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting()});
function isShell(request){const u=new URL(request.url);return request.mode==="navigate"||/\/(?:index\.html|app\.js|styles\.css|material-engine\.js|apex\.css)$/.test(u.pathname)}
async function networkFirst(request){try{const response=await fetch(request,{cache:"no-store"});if(response&&response.status===200){const cache=await caches.open(CACHE);cache.put(request,response.clone())}return response}catch(_){return (await caches.match(request))||(await caches.match("./index.html?v=018"))}}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;if(isShell(event.request)){event.respondWith(networkFirst(event.request));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(!response||response.status!==200||response.type==="opaque")return response;const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}))) });
