function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function blockEnd(b){return b.openEnd?"Sin fecha":addDays(b.startDate||today(),((+b.weeks||1)+(b.deload?1:0))*7-1)}
function blockPct(b){if(b.openEnd)return{cur:1,tot:"∞",pct:20};let st=new Date(b.startDate||today()),nw=new Date(today()),tot=(+b.weeks||1)+(b.deload?1:0);let cur=Math.floor((nw-st)/(7*86400000))+1;return{cur:Math.max(1,cur),tot,pct:Math.max(0,Math.min(100,Math.round(cur/tot*100)))}}
function newBlock(){S.blocks.push({id:id(),name:"Bloque personalizado",type:"Personalizado",startDate:today(),weeks:6,deload:false,openEnd:false,objective:"",note:"",routineIds:[]});save();GT.render()}
function delBlock(bid){let b=S.blocks.find(x=>x.id===bid);if(confirm("¿Mover bloque a papelera?")){S.trash=S.trash||{routines:[],blocks:[],sessions:[]};if(b)S.trash.blocks.push({...b,deletedAt:now()});S.blocks=S.blocks.filter(x=>x.id!==bid);save();GT.render()}}
function updBlock(bid,k,v){let b=S.blocks.find(x=>x.id===bid);if(!b)return;if(k==="weeks")v=+v;if(k==="deload"||k==="openEnd")v=v==="true";b[k]=v;save()}
function toggleRoutineBlock(bid,rid){let b=S.blocks.find(x=>x.id===bid);b.routineIds=b.routineIds||[];b.routineIds.includes(rid)?b.routineIds=b.routineIds.filter(x=>x!==rid):b.routineIds.push(rid);save();GT.render()}
function setWeekRoutine(day,rid){S.weekPlan=S.weekPlan||{};if(rid)S.weekPlan[day]=rid;else delete S.weekPlan[day];save();GT.render()}
function applyWeekToToday(){let d=new Date().getDay();let map=["sun","mon","tue","wed","thu","fri","sat"];let rid=S.weekPlan?.[map[d]];if(rid){S.plan[today()]={date:today(),type:"train",routineId:rid,status:"pending"};save();GT.render();alert("Rutina de hoy aplicada")}else alert("Hoy está marcado como descanso o sin rutina")}
function renderWeekPlan(){let days=[["mon","Lunes"],["tue","Martes"],["wed","Miércoles"],["thu","Jueves"],["fri","Viernes"],["sat","Sábado"],["sun","Domingo"]];return `<div class="card"><h2>Plan semanal</h2><p class="muted">Asigna una rutina a cada día. Sin rutina = descanso.</p><button class="wall primary" onclick="applyWeekToToday()">Aplicar lo que toca hoy</button><div class="weekGrid">${days.map(([k,n])=>`<div class="dayPlan"><h3>${n}</h3><select onchange="setWeekRoutine('${k}',this.value)"><option value="">Descanso / libre</option>${S.routines.map(r=>`<option value="${r.id}" ${S.weekPlan?.[k]===r.id?"selected":""}>${r.name}</option>`).join("")}</select></div>`).join("")}</div></div>`}
function renderPlan(){let cards=S.blocks.map(b=>{let p=blockPct(b);b.routineIds=b.routineIds||[];return`<div class="block"><strong>${b.name}</strong><p class="muted">${b.type} · semana ${p.cur}/${p.tot} · ${b.startDate||today()} → ${blockEnd(b)}</p><div class="bar"><span style="width:${p.pct}%"></span></div><div class="grid"><input value="${b.name||""}" onchange="updBlock('${b.id}','name',this.value)"><select onchange="updBlock('${b.id}','type',this.value)"><option ${b.type==="Fuerza"?"selected":""}>Fuerza</option><option ${b.type==="Hipertrofia"?"selected":""}>Hipertrofia</option><option ${b.type==="Técnica"?"selected":""}>Técnica</option><option ${b.type==="Deload"?"selected":""}>Deload</option><option ${b.type==="Personalizado"?"selected":""}>Personalizado</option></select><input type="date" value="${b.startDate||today()}" onchange="updBlock('${b.id}','startDate',this.value)"><input type="number" value="${b.weeks||6}" onchange="updBlock('${b.id}','weeks',this.value)"></div><input placeholder="Objetivo del bloque" value="${b.objective||""}" onchange="updBlock('${b.id}','objective',this.value)"><textarea placeholder="Notas" onchange="updBlock('${b.id}','note',this.value)">${b.note||""}</textarea><h3>Rutinas del bloque</h3><div class="blockRoutineGrid">${S.routines.map(r=>`<label class="checkRow"><input type="checkbox" ${b.routineIds.includes(r.id)?"checked":""} onchange="toggleRoutineBlock('${b.id}','${r.id}')"> ${r.name}</label>`).join("")||"<p class='muted'>No hay rutinas.</p>"}</div><button class="danger" onclick="delBlock('${b.id}')">Borrar bloque</button></div>`}).join("");return`${renderWeekPlan()}<div class="card"><h2>Bloques personalizados</h2><button class="wall primary" onclick="newBlock()">Nuevo bloque</button>${cards}</div>`}